### ISSUE TITLE
Progress Tracker:  Celtic Data

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#473]
See also:  #468.

----
## New Recordings to Segment and Upload
- [x] Clt_Bryth_Wel_Pat_Atl_Dolavon_Dl
- [x] Clt_Bryth_Wel_Pat_Atl_GaimanSkr1_Dl
- [x] Clt_Bryth_Wel_Pat_Atl_GaimanSkr2_Dl
- [x] Clt_Bryth_Wel_Pat_Atl_LleCul_Dl
- [x] Clt_Bryth_Wel_Pat_And_Esquel_Dl

@cormacanderson -- ideally also transcribe 4 and 5 in these varietiex  New Excel transcription sheet will be provided soon.
